//! TypeScript generator: interfaces, discriminated unions, and action creators.

use std::fmt::Write;

use crate::model::{Def, Error, Field, Model, Ty};
use crate::names::doc_line;

fn ty(t: &Ty) -> String {
    match t {
        Ty::Bool => "boolean".into(),
        Ty::Int(_) | Ty::Float => "number".into(),
        Ty::Str => "string".into(),
        Ty::Json => "unknown".into(),
        Ty::Named(n) => n.clone(),
        Ty::Optional(i) => format!("{} | null", ty(i)),
        Ty::Array(i) => match &**i {
            Ty::Optional(_) => format!("({})[]", ty(i)),
            _ => format!("{}[]", ty(i)),
        },
        Ty::Map(i) => format!("Record<string, {}>", ty(i)),
    }
}

fn key(s: &str) -> String {
    let ok = s
        .chars()
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_' || c == '$')
        && s.chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$');
    if ok {
        s.to_string()
    } else {
        format!("{s:?}")
    }
}

/// `out_only`: only the core writes this type, so a default means "always present".
fn field(f: &Field, out_only: bool) -> String {
    let absent_ok = f.optional && !(out_only && f.default.is_some());
    let opt = absent_ok || matches!(f.ty, Ty::Optional(_));
    format!(
        "{}{}: {}",
        key(&f.json),
        if opt { "?" } else { "" },
        ty(&f.ty)
    )
}

fn doc(o: &mut String, indent: &str, d: &Option<String>) {
    if let Some(d) = d {
        let _ = writeln!(o, "{indent}/** {} */", doc_line(&d.replace('\n', " ")));
    }
}

fn root_name(t: &Ty, what: &str) -> Result<String, Error> {
    match t {
        Ty::Named(n) => Ok(n.clone()),
        _ => Err(Error(format!(
            "the app's {what} type must be a struct or enum, not an inline type"
        ))),
    }
}

pub fn generate(m: &Model) -> Result<String, Error> {
    let mut o = String::new();
    let _ = writeln!(
        o,
        "// Generated by cargo-carapace from the {} core schema. Do not edit.",
        m.app
    );
    let _ = writeln!(o, "// Regenerate with: cargo carapace gen ts\n");
    let _ = writeln!(o, "export const appName = {:?};", m.app);
    let _ = writeln!(o, "export const schemaHash = \"0x{:016x}\";\n", m.hash);

    for t in &m.types {
        if m.event.is_none() && t.name == "NoEvent" {
            continue;
        }
        doc(&mut o, "", &t.doc);
        let out_only = m.output_only.contains(&t.name);
        match &t.def {
            Def::Cases { cases } => {
                let lits: Vec<String> = cases.iter().map(|c| format!("{c:?}")).collect();
                let _ = writeln!(o, "export type {} = {};\n", t.name, lits.join(" | "));
            }
            Def::Struct { fields } => {
                let _ = writeln!(o, "export interface {} {{", t.name);
                for f in fields {
                    doc(&mut o, "  ", &f.doc);
                    let _ = writeln!(o, "  {};", field(f, out_only));
                }
                o.push_str("}\n\n");
            }
            Def::Union { tag_key, variants } => {
                let _ = writeln!(o, "export type {} =", t.name);
                for v in variants {
                    doc(&mut o, "  ", &v.doc);
                    let mut parts = vec![format!("{}: {:?}", key(tag_key), v.tag)];
                    parts.extend(v.fields.iter().map(|f| field(f, out_only)));
                    let _ = writeln!(o, "  | {{ {} }}", parts.join("; "));
                }
                o.push_str(";\n\n");
            }
        }
    }

    let action = root_name(&m.action, "Action")?;
    if let Some(Def::Union { tag_key, variants }) = m.index.get(&action).map(|i| &m.types[*i].def) {
        let _ = writeln!(
            o,
            "/** Typed constructors for every action. */\nexport const actions = {{"
        );
        for v in variants {
            let params: Vec<String> = v.fields.iter().map(|f| field(f, false)).collect();
            let names: Vec<String> = v.fields.iter().map(|f| key(&f.json)).collect();
            let name = key(&v.tag);
            if v.fields.is_empty() {
                let _ = writeln!(
                    o,
                    "  {name}: (): {action} => ({{ {}: {:?} }}),",
                    key(tag_key),
                    v.tag
                );
            } else {
                // Object-parameter form keeps call sites readable and order-independent.
                let _ = writeln!(
                    o,
                    "  {name}: (a: {{ {} }}): {action} => ({{ {}: {:?}, {} }}),",
                    params.join("; "),
                    key(tag_key),
                    v.tag,
                    names
                        .iter()
                        .map(|n| format!("{n}: a.{n}"))
                        .collect::<Vec<_>>()
                        .join(", ")
                );
            }
        }
        o.push_str("};\n\n");
    }

    let event = match &m.event {
        Some(t) => root_name(t, "Event")?,
        None => "never".to_string(),
    };
    let (query, answer) = match &m.query {
        Some((q, a)) => (root_name(q, "Query")?, root_name(a, "Answer")?),
        None => ("never".to_string(), "never".to_string()),
    };
    let _ = writeln!(
        o,
        "/** The types a Carapace client is generic over. */\nexport interface Types {{\n  state: {};\n  action: {action};\n  event: {event};\n  config: {};\n  query: {query};\n  answer: {answer};\n}}",
        root_name(&m.state, "State")?,
        root_name(&m.config, "Config")?
    );
    Ok(o)
}
