// Generated by cargo-carapace from the Counter core schema. Do not edit.
// Regenerate with: cargo carapace gen ts

export const appName = "Counter";
export const schemaHash = "0xaa46f2524ab6eb7a";

export type Mode = "idle" | "ticking" | "fetching";

export interface State {
  count: number;
  step: number;
  mode: Mode;
  history: number[];
  label?: string | null;
}

export type Action =
  | { type: "increment" }
  | { type: "decrement" }
  | { type: "setStep"; step: number }
  | { type: "rename"; label?: string | null }
  | { type: "startTicking" }
  | { type: "stopTicking" }
  | { type: "tick" }
  /** Pretend to do slow work off the core thread, then report back. */
  | { type: "fetch" }
  | { type: "fetched"; value: number }
  | { type: "reset" }
;

export interface Config {
  /** Where the counter starts. */
  start?: number;
}

export type Event =
  /** The shell should show a notification. */
  | { type: "notify"; title: string; body: string }
;

/** Pure helpers the shell can call without going through state. */
export type Query =
  /** Describe a number in words the UI can show. */
  | { type: "describe"; value: number }
;

export interface Answer {
  text: string;
}

/** Typed constructors for every action. */
export const actions = {
  increment: (): Action => ({ type: "increment" }),
  decrement: (): Action => ({ type: "decrement" }),
  setStep: (a: { step: number }): Action => ({ type: "setStep", step: a.step }),
  rename: (a: { label?: string | null }): Action => ({ type: "rename", label: a.label }),
  startTicking: (): Action => ({ type: "startTicking" }),
  stopTicking: (): Action => ({ type: "stopTicking" }),
  tick: (): Action => ({ type: "tick" }),
  fetch: (): Action => ({ type: "fetch" }),
  fetched: (a: { value: number }): Action => ({ type: "fetched", value: a.value }),
  reset: (): Action => ({ type: "reset" }),
};

/** The types a Carapace client is generic over. */
export interface Types {
  state: State;
  action: Action;
  event: Event;
  config: Config;
  query: Query;
  answer: Answer;
}
