// Generated by cargo-carapace from the Counter core schema. Do not edit.
// Regenerate with: cargo carapace gen swift

import Foundation
import CarapaceKit

public enum Counter: CarapaceApp {
    public static let name = "Counter"
    public static let schemaHash: UInt64 = 0xd26c8e19d702c8cd


    public enum Mode: String, Codable, Sendable, Hashable, CaseIterable {
        case idle
        case ticking
        case fetching
    }

    public struct State: Codable, Sendable, Hashable {
        public var count: Int
        public var step: Int
        public var mode: Mode
        public var history: [Int]
        public var label: String?

        public init(count: Int, step: Int, mode: Mode, history: [Int], label: String? = nil) {
            self.count = count
            self.step = step
            self.mode = mode
            self.history = history
            self.label = label
        }
    }

    public indirect enum Action: Sendable, Hashable {
        case increment
        case decrement
        case setStep(step: Int)
        case rename(label: String? = nil)
        case startTicking
        case stopTicking
        case tick
        /// Pretend to do slow work off the core thread, then report back.
        case fetch
        case fetched(value: Int)
        case reset
        /// Ask the core for a `Summary` event.
        case summarize
    }

    public struct Config: Codable, Sendable, Hashable {
        /// Where the counter starts.
        public var start: Int

        public init(start: Int = 0) {
            self.start = start
        }

        enum CodingKeys: Swift.String, Swift.CodingKey {
            case start
        }

        public init(from decoder: Swift.Decoder) throws {
            let c = try decoder.container(keyedBy: CodingKeys.self)
            self.start = try c.decodeIfPresent(Int.self, forKey: .start) ?? 0
        }
    }

    /// A newtype variant: the struct's fields sit next to the tag in JSON.
    public struct Summary: Codable, Sendable, Hashable {
        public var count: Int
        public var entries: Int

        public init(count: Int, entries: Int) {
            self.count = count
            self.entries = entries
        }
    }

    public indirect enum Event: Sendable, Hashable {
        /// The shell should show a notification.
        case notify(title: String, body: String)
        /// A snapshot of where the counter stands, on request.
        case summary(count: Int, entries: Int)
    }

    /// Pure helpers the shell can call without going through state.
    public indirect enum Query: Sendable, Hashable {
        /// Describe a number in words the UI can show.
        case describe(value: Int)
    }

    public struct Answer: Codable, Sendable, Hashable {
        public var text: String

        public init(text: String) {
            self.text = text
        }
    }

}

extension Counter.Action: Codable {
    private struct Key: Swift.CodingKey {
        var stringValue: String
        var intValue: Int? { nil }
        init(_ s: String) { stringValue = s }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { nil }
    }

    public init(from decoder: Swift.Decoder) throws {
        let c = try decoder.container(keyedBy: Key.self)
        let tag = try c.decode(String.self, forKey: Key("type"))
        switch tag {
        case "increment": self = .increment
        case "decrement": self = .decrement
        case "setStep":
            let v0 = try c.decode(Int.self, forKey: Key("step"))
            self = .setStep(step: v0)
        case "rename":
            let v0 = try c.decodeIfPresent(String.self, forKey: Key("label"))
            self = .rename(label: v0)
        case "startTicking": self = .startTicking
        case "stopTicking": self = .stopTicking
        case "tick": self = .tick
        case "fetch": self = .fetch
        case "fetched":
            let v0 = try c.decode(Int.self, forKey: Key("value"))
            self = .fetched(value: v0)
        case "reset": self = .reset
        case "summarize": self = .summarize
        default:
            throw Swift.DecodingError.dataCorruptedError(forKey: Key("type"), in: c, debugDescription: "unknown Action type \(tag)")
        }
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var c = encoder.container(keyedBy: Key.self)
        switch self {
        case .increment:
            try c.encode("increment", forKey: Key("type"))
        case .decrement:
            try c.encode("decrement", forKey: Key("type"))
        case .setStep(let v0):
            try c.encode("setStep", forKey: Key("type"))
            try c.encode(v0, forKey: Key("step"))
        case .rename(let v0):
            try c.encode("rename", forKey: Key("type"))
            try c.encodeIfPresent(v0, forKey: Key("label"))
        case .startTicking:
            try c.encode("startTicking", forKey: Key("type"))
        case .stopTicking:
            try c.encode("stopTicking", forKey: Key("type"))
        case .tick:
            try c.encode("tick", forKey: Key("type"))
        case .fetch:
            try c.encode("fetch", forKey: Key("type"))
        case .fetched(let v0):
            try c.encode("fetched", forKey: Key("type"))
            try c.encode(v0, forKey: Key("value"))
        case .reset:
            try c.encode("reset", forKey: Key("type"))
        case .summarize:
            try c.encode("summarize", forKey: Key("type"))
        }
    }
}

extension Counter.Event: Codable {
    private struct Key: Swift.CodingKey {
        var stringValue: String
        var intValue: Int? { nil }
        init(_ s: String) { stringValue = s }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { nil }
    }

    public init(from decoder: Swift.Decoder) throws {
        let c = try decoder.container(keyedBy: Key.self)
        let tag = try c.decode(String.self, forKey: Key("type"))
        switch tag {
        case "notify":
            let v0 = try c.decode(String.self, forKey: Key("title"))
            let v1 = try c.decode(String.self, forKey: Key("body"))
            self = .notify(title: v0, body: v1)
        case "summary":
            let v0 = try c.decode(Int.self, forKey: Key("count"))
            let v1 = try c.decode(Int.self, forKey: Key("entries"))
            self = .summary(count: v0, entries: v1)
        default:
            throw Swift.DecodingError.dataCorruptedError(forKey: Key("type"), in: c, debugDescription: "unknown Event type \(tag)")
        }
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var c = encoder.container(keyedBy: Key.self)
        switch self {
        case .notify(let v0, let v1):
            try c.encode("notify", forKey: Key("type"))
            try c.encode(v0, forKey: Key("title"))
            try c.encode(v1, forKey: Key("body"))
        case .summary(let v0, let v1):
            try c.encode("summary", forKey: Key("type"))
            try c.encode(v0, forKey: Key("count"))
            try c.encode(v1, forKey: Key("entries"))
        }
    }
}

extension Counter.Query: Codable {
    private struct Key: Swift.CodingKey {
        var stringValue: String
        var intValue: Int? { nil }
        init(_ s: String) { stringValue = s }
        init?(stringValue: String) { self.stringValue = stringValue }
        init?(intValue: Int) { nil }
    }

    public init(from decoder: Swift.Decoder) throws {
        let c = try decoder.container(keyedBy: Key.self)
        let tag = try c.decode(String.self, forKey: Key("type"))
        switch tag {
        case "describe":
            let v0 = try c.decode(Int.self, forKey: Key("value"))
            self = .describe(value: v0)
        default:
            throw Swift.DecodingError.dataCorruptedError(forKey: Key("type"), in: c, debugDescription: "unknown Query type \(tag)")
        }
    }

    public func encode(to encoder: Swift.Encoder) throws {
        var c = encoder.container(keyedBy: Key.self)
        switch self {
        case .describe(let v0):
            try c.encode("describe", forKey: Key("type"))
            try c.encode(v0, forKey: Key("value"))
        }
    }
}

public typealias CounterStore = Store<Counter>
