//! The stable C ABI. Every function is `extern "C"`, takes and returns plain
//! pointers and lengths, and moves JSON text. Generated by [`export!`](crate::export).
//!
//! Ownership rules, identical for every host language:
//! - strings returned as `*mut c_char` are owned by the caller; free with `carapace_string_free`.
//! - a handle from `carapace_start` is freed with `carapace_stop`.
//! - the subscription callback runs on the core thread; copy what you need and return.

use std::ffi::{c_char, c_void, CStr, CString};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::ptr;

use crate::engine::{App, Queries};
use crate::runtime::{Handle, Notice, Runtime};
use crate::schema::{schema_hash, ABI_VERSION};

/// Callback signature. `kind`: 0 state, 1 event, 2 fault. `data` is UTF-8, not NUL-terminated.
pub type Callback = extern "C" fn(user: *mut c_void, kind: u32, data: *const u8, len: usize);

/// The type-erased runtime behind a `CarapaceHandle`.
pub trait Erased: Send {
    fn dispatch(&self, json: &str) -> Result<(), String>;
    fn dispatch_wait(&self, json: &str) -> Result<(), String>;
    fn snapshot(&self) -> String;
    fn subscribe(&self, cb: Callback, user: *mut c_void) -> u64;
    fn unsubscribe(&self, id: u64);
}

struct Live<A: App>(Runtime<A>);

struct SendPtr(*mut c_void);
// SAFETY: the host promises `user` is usable from the core thread; it is only passed back to the callback.
unsafe impl Send for SendPtr {}
unsafe impl Sync for SendPtr {}

impl<A: App> Erased for Live<A> {
    fn dispatch(&self, json: &str) -> Result<(), String> {
        self.0.dispatch_json(json).map_err(|e| e.to_string())
    }
    fn dispatch_wait(&self, json: &str) -> Result<(), String> {
        self.0
            .dispatch_json_wait(json)
            .map(|_| ())
            .map_err(|e| e.to_string())
    }
    fn snapshot(&self) -> String {
        self.0.snapshot().to_string()
    }
    fn subscribe(&self, cb: Callback, user: *mut c_void) -> u64 {
        let user = SendPtr(user);
        self.0.subscribe(move |notice| {
            let (kind, data) = match notice {
                Notice::State(s) => (0, s),
                Notice::Event(s) => (1, s),
                Notice::Fault(s) => (2, s),
            };
            let user = &user;
            cb(user.0, kind, data.as_ptr(), data.len());
        })
    }
    fn unsubscribe(&self, id: u64) {
        self.0.unsubscribe(id);
    }
}

/// Opaque handle given to hosts.
pub struct CarapaceHandle(Box<dyn Erased>);

fn to_c(s: impl Into<Vec<u8>>) -> *mut c_char {
    let mut bytes: Vec<u8> = s.into();
    bytes.retain(|b| *b != 0);
    CString::new(bytes)
        .map(CString::into_raw)
        .unwrap_or(ptr::null_mut())
}

fn panic_text(p: Box<dyn std::any::Any + Send>) -> String {
    p.downcast_ref::<&str>()
        .map(|s| s.to_string())
        .or_else(|| p.downcast_ref::<String>().cloned())
        .unwrap_or_else(|| "non-string panic".into())
}

/// Start a core. `config` is a JSON object (or null/empty for defaults).
/// On failure returns null and writes an owned error string to `*error`.
///
/// # Safety
/// `config` is null or a NUL-terminated string; `error` is null or a valid out-pointer.
pub unsafe fn start<A: App>(config: *const c_char, error: *mut *mut c_char) -> *mut CarapaceHandle {
    let result = catch_unwind(AssertUnwindSafe(
        || -> Result<*mut CarapaceHandle, String> {
            let text = if config.is_null() {
                ""
            } else {
                // SAFETY: the host passes a NUL-terminated string.
                unsafe { CStr::from_ptr(config) }
                    .to_str()
                    .map_err(|e| format!("config is not UTF-8: {e}"))?
            };
            let config: A::Config = if text.trim().is_empty() {
                A::Config::default()
            } else {
                serde_json::from_str(text)
                    .map_err(|e| format!("{}: cannot decode config ({e})", A::NAME))?
            };
            let rt = Runtime::<A>::start(config);
            Ok(Box::into_raw(Box::new(CarapaceHandle(Box::new(Live(rt))))))
        },
    ));
    let message = match result {
        Ok(Ok(handle)) => return handle,
        Ok(Err(m)) => m,
        Err(p) => format!("{}: start panicked: {}", A::NAME, panic_text(p)),
    };
    if !error.is_null() {
        // SAFETY: `error` is a valid out-pointer when non-null.
        unsafe { *error = to_c(message) };
    }
    ptr::null_mut()
}

/// Queue an action. Returns null on success or an owned error string.
///
/// # Safety
/// `handle` must come from `carapace_start`; `json` must point to `len` readable bytes.
pub unsafe fn dispatch(handle: *mut CarapaceHandle, json: *const u8, len: usize) -> *mut c_char {
    if handle.is_null() || json.is_null() {
        return to_c("carapace_dispatch: null handle or json");
    }
    let bytes = std::slice::from_raw_parts(json, len);
    let text = match std::str::from_utf8(bytes) {
        Ok(t) => t,
        Err(e) => return to_c(format!("carapace_dispatch: action is not UTF-8: {e}")),
    };
    match catch_unwind(AssertUnwindSafe(|| (*handle).0.dispatch(text))) {
        Ok(Ok(())) => ptr::null_mut(),
        Ok(Err(m)) => to_c(m),
        Err(p) => to_c(format!("carapace_dispatch panicked: {}", panic_text(p))),
    }
}

/// Like [`dispatch`], but returns only after the action was processed and subscribers were
/// notified. Never call from inside a subscription callback.
///
/// # Safety
/// `handle` must come from `carapace_start`; `json` must point to `len` readable bytes.
pub unsafe fn dispatch_wait(
    handle: *mut CarapaceHandle,
    json: *const u8,
    len: usize,
) -> *mut c_char {
    if handle.is_null() || json.is_null() {
        return to_c("carapace_dispatch_wait: null handle or json");
    }
    let text = match std::str::from_utf8(std::slice::from_raw_parts(json, len)) {
        Ok(t) => t,
        Err(e) => return to_c(format!("carapace_dispatch_wait: action is not UTF-8: {e}")),
    };
    match catch_unwind(AssertUnwindSafe(|| (*handle).0.dispatch_wait(text))) {
        Ok(Ok(())) => ptr::null_mut(),
        Ok(Err(m)) => to_c(m),
        Err(p) => to_c(format!(
            "carapace_dispatch_wait panicked: {}",
            panic_text(p)
        )),
    }
}

/// # Safety
/// `handle` must come from `carapace_start`.
pub unsafe fn state(handle: *mut CarapaceHandle) -> *mut c_char {
    if handle.is_null() {
        return ptr::null_mut();
    }
    to_c((*handle).0.snapshot())
}

/// # Safety
/// `handle` must come from `carapace_start`; `user` must stay valid until unsubscribed or stopped.
pub unsafe fn subscribe(handle: *mut CarapaceHandle, cb: Callback, user: *mut c_void) -> u64 {
    if handle.is_null() {
        return 0;
    }
    (*handle).0.subscribe(cb, user)
}

/// # Safety
/// `handle` must come from `carapace_start`.
pub unsafe fn unsubscribe(handle: *mut CarapaceHandle, id: u64) {
    if !handle.is_null() {
        (*handle).0.unsubscribe(id);
    }
}

/// # Safety
/// `handle` must come from `carapace_start` and is invalid afterwards.
pub unsafe fn stop(handle: *mut CarapaceHandle) {
    if !handle.is_null() {
        drop(Box::from_raw(handle));
    }
}

/// # Safety
/// `s` must come from a carapace function that returns an owned string.
pub unsafe fn string_free(s: *mut c_char) {
    if !s.is_null() {
        drop(CString::from_raw(s));
    }
}

pub fn schema_json(schema: fn() -> serde_json::Value) -> *mut c_char {
    to_c(serde_json::to_string(&schema()).unwrap_or_default())
}

pub fn hash(schema: fn() -> serde_json::Value) -> u64 {
    schema_hash(&schema())
}

/// Run a pure query. Returns the answer JSON, or null with `*error` set.
///
/// # Safety
/// `json` must point to `len` readable bytes; `error` is null or a valid out-pointer.
pub unsafe fn query<A: Queries>(
    json: *const u8,
    len: usize,
    error: *mut *mut c_char,
) -> *mut c_char {
    let fail = |message: String| {
        if !error.is_null() {
            *error = to_c(message);
        }
        ptr::null_mut()
    };
    if json.is_null() {
        return fail("carapace_query: null json".into());
    }
    let text = match std::str::from_utf8(std::slice::from_raw_parts(json, len)) {
        Ok(t) => t,
        Err(e) => return fail(format!("carapace_query: query is not UTF-8: {e}")),
    };
    let result = catch_unwind(AssertUnwindSafe(|| crate::runtime::query_json::<A>(text)));
    match result {
        Ok(Ok(answer)) => to_c(answer),
        Ok(Err(m)) => fail(m),
        Err(p) => fail(format!("{}: query panicked: {}", A::NAME, panic_text(p))),
    }
}

/// The `carapace_query` for cores that export no queries.
///
/// # Safety
/// `error` is null or a valid out-pointer.
pub unsafe fn query_unsupported(app: &str, error: *mut *mut c_char) -> *mut c_char {
    if !error.is_null() {
        *error = to_c(format!(
            "{app}: this core exports no queries; use `carapace::export!({app}, queries)`"
        ));
    }
    ptr::null_mut()
}

pub const fn abi_version() -> u32 {
    ABI_VERSION
}

/// Re-exported so the macro can name it without the caller importing it.
pub type DispatchHandle<A> = Handle<A>;
